<a href="https://colab.research.google.com/github/Anudivya-Geddada/FML/blob/main/Logestic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Logestic Regression on diabetes dataset

First we have to import all the needed libraries and functions

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Read the csv file using pandas library

 Here the head method returns the first 6 rows of the given dataset

In [6]:
data = pd.read_csv("diabetes.csv")
data.head(6)

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   
5            5      116         74        0        0  25.6  0.201   30   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1  
5         0

Now Remove the labeled data from the input data using drop method

In [7]:
X = data.drop('diabetes', axis=1).values
y = data['diabetes'].values

In [8]:
X.shape, y.shape

((768, 8), (768,))

In [11]:
X[0], y[0]

(array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ]), 1)

In [12]:
np.unique(y)

array([0, 1])

split the given data into training data and testing data

In [15]:
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, test_size=0.2, random_state=0)

Now we have to standardize our data i.e Scale the training data whose mean of each column must be equal to zero and standard deviation should be one

In [14]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([  7.   , 150.   ,  78.   ,  29.   , 126.   ,  35.2  ,   0.692,
         54.   ]), 59.9865, 50.89017268343663)

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

After standardise our data,the mean and standard deviation are

In [17]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([0.90832902, 0.91569367, 0.44912368, 0.52222619, 0.3736349 ,
        0.37852648, 0.67740401, 1.69955804]),
 0.7405620009571598,
 0.41545024515724205)

create a model and train it
fit the hyper-parameter c

In [19]:
model = LogisticRegression(C=0.08, multi_class='ovr',random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=0.08, multi_class='ovr', random_state=0)

Scale the testing data

In [20]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

Measure the performances of training data and testing data

In [22]:
model.score(X_train, y_train)

0.755700325732899

In [23]:
model.score(X_test, y_test)


0.8246753246753247

construct a confusion matrix for the actual label data and predicted label data

In [24]:
confusion_matrix(y_test, y_pred)

array([[98,  9],
       [18, 29]])

Find the evaluation metrics for classification are accuracy,precision,recall and f1-score

In [25]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154

