<a href="https://colab.research.google.com/github/Anudivya-Geddada/FML/blob/main/Logestic_Regression_on_Multiclass_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Multiclass Logestic Regression on Iris dataset

Import all the needed libraries and Packages

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

Load the data in iris dataset

In [2]:
iris=load_iris()

In [4]:
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


Now split the data into training data and testing data by using the train_test_split method

In [8]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.1, random_state=40)

Here one vs rest approach is suitable for multiclass logestic regression. 
Fit the hyper-parameter(c) and training data

In [9]:
model = LogisticRegression(C=5, multi_class='ovr',random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=5, multi_class='ovr', random_state=0)

In [15]:
y_pred = model.predict(X_test)

Measure the performance of training data and testing data

In [10]:
model.score(X_train, y_train)

0.9703703703703703

In [11]:
model.score(X_test, y_test)

1.0

Confusion matrix for the actual label data and predicted label data

In [17]:
confusion_matrix(y_test, y_pred)

array([[4, 0, 0],
       [0, 7, 0],
       [0, 0, 4]])

we have to find the Evaluation metrics of Classification are accuracy,precision,recall and f1-measure

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

